package frames;

import java.awt.*;
import javax.swing.*;

/**
 * Pantalla principal del sistema
 *
 * @author victoria
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private JPanel panel;

    public FrmPrincipal() {
        initComponents();
        pintarContenedor(new PnlInicio());
        this.setTitle("Grafo del estado de Puebla - Inicio");

    }

    public void pintarContenedor(JPanel panel) {
        pnlContenido.setViewportView(panel);
        pnlContenido.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        pnlContenido.revalidate();
        pnlContenido.repaint();
        panel.revalidate();
        panel.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JScrollPane();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnInicio = new javax.swing.JMenu();
        btnGrafo = new javax.swing.JMenu();
        btnTablaNodosAristas = new javax.swing.JMenuItem();
        btnGrafico = new javax.swing.JMenuItem();
        bntRecorridos = new javax.swing.JMenu();
        btnBFS = new javax.swing.JMenuItem();
        btnDFS = new javax.swing.JMenuItem();
        btnMST = new javax.swing.JMenu();
        btnKruskal = new javax.swing.JMenuItem();
        btnPrim = new javax.swing.JMenuItem();
        btnBoruvka = new javax.swing.JMenuItem();
        btnRuta = new javax.swing.JMenu();
        btnBellmanFord = new javax.swing.JMenuItem();
        btnDijkstra = new javax.swing.JMenuItem();
        btnReportesComplejidad = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1700, 900));

        pnlContenedor.setSize(new java.awt.Dimension(100, 70));

        pnlContenido.setBorder(null);
        pnlContenido.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlContenido.setPreferredSize(new java.awt.Dimension(2000, 900));

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContenedor, java.awt.BorderLayout.CENTER);

        menu.setBorder(null);
        menu.setPreferredSize(new java.awt.Dimension(307, 100));

        jMenu1.setEnabled(false);
        jMenu1.setPreferredSize(new java.awt.Dimension(56, 26));
        menu.add(jMenu1);

        btnInicio.setBorder(null);
        btnInicio.setText("Inicio");
        btnInicio.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInicio.setPreferredSize(new java.awt.Dimension(150, 23));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        menu.add(btnInicio);

        btnGrafo.setBorder(null);
        btnGrafo.setText("Grafo");
        btnGrafo.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        btnGrafo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGrafo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrafo.setPreferredSize(new java.awt.Dimension(150, 23));

        btnTablaNodosAristas.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnTablaNodosAristas.setText("Tabla de vértices y aristas");
        btnTablaNodosAristas.setPreferredSize(new java.awt.Dimension(209, 40));
        btnTablaNodosAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaNodosAristasActionPerformed(evt);
            }
        });
        btnGrafo.add(btnTablaNodosAristas);

        btnGrafico.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnGrafico.setText("Vista gráfica");
        btnGrafico.setPreferredSize(new java.awt.Dimension(131, 40));
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });
        btnGrafo.add(btnGrafico);

        menu.add(btnGrafo);

        bntRecorridos.setBorder(null);
        bntRecorridos.setText("Recorridos");
        bntRecorridos.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        bntRecorridos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bntRecorridos.setPreferredSize(new java.awt.Dimension(150, 23));

        btnBFS.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnBFS.setText("BFS (anchura)");
        btnBFS.setPreferredSize(new java.awt.Dimension(128, 40));
        btnBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBFSActionPerformed(evt);
            }
        });
        bntRecorridos.add(btnBFS);

        btnDFS.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnDFS.setText("DFS (profundidad)");
        btnDFS.setPreferredSize(new java.awt.Dimension(153, 40));
        btnDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDFSActionPerformed(evt);
            }
        });
        bntRecorridos.add(btnDFS);

        menu.add(bntRecorridos);

        btnMST.setBorder(null);
        btnMST.setText("Árbol de expansión mínima");
        btnMST.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        btnMST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMST.setPreferredSize(new java.awt.Dimension(300, 23));

        btnKruskal.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnKruskal.setText("Kruskal");
        btnKruskal.setPreferredSize(new java.awt.Dimension(128, 40));
        btnKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKruskalActionPerformed(evt);
            }
        });
        btnMST.add(btnKruskal);

        btnPrim.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnPrim.setText("Prim");
        btnPrim.setPreferredSize(new java.awt.Dimension(74, 40));
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });
        btnMST.add(btnPrim);

        btnBoruvka.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnBoruvka.setText("Borůvka");
        btnBoruvka.setPreferredSize(new java.awt.Dimension(96, 40));
        btnBoruvka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoruvkaActionPerformed(evt);
            }
        });
        btnMST.add(btnBoruvka);

        menu.add(btnMST);

        btnRuta.setBorder(null);
        btnRuta.setText("Ruta más corta");
        btnRuta.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        btnRuta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRuta.setPreferredSize(new java.awt.Dimension(200, 23));

        btnBellmanFord.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnBellmanFord.setText("Bellman-Ford");
        btnBellmanFord.setPreferredSize(new java.awt.Dimension(126, 40));
        btnBellmanFord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBellmanFordActionPerformed(evt);
            }
        });
        btnRuta.add(btnBellmanFord);

        btnDijkstra.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N
        btnDijkstra.setText("Dijkstra");
        btnDijkstra.setPreferredSize(new java.awt.Dimension(92, 40));
        btnDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDijkstraActionPerformed(evt);
            }
        });
        btnRuta.add(btnDijkstra);

        menu.add(btnRuta);

        btnReportesComplejidad.setBorder(null);
        btnReportesComplejidad.setText("Reportes de complejidad");
        btnReportesComplejidad.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        btnReportesComplejidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReportesComplejidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportesComplejidad.setPreferredSize(new java.awt.Dimension(250, 23));
        btnReportesComplejidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesComplejidadMouseClicked(evt);
            }
        });
        menu.add(btnReportesComplejidad);

        btnSalir.setBorder(null);
        btnSalir.setText("Salir");
        btnSalir.setFont(new java.awt.Font("Beirut", 0, 18)); // NOI18N
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setPreferredSize(new java.awt.Dimension(150, 23));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        menu.add(btnSalir);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        pintarContenedor(new PnlInicio());
        this.setTitle("Grafo del estado de Puebla - Inicio");
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnTablaNodosAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaNodosAristasActionPerformed
        FrmTablaGrafo tablaGrafo = new FrmTablaGrafo();
        tablaGrafo.setVisible(true);
    }//GEN-LAST:event_btnTablaNodosAristasActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        this.setTitle("Grafo del estado de Puebla - Representación gráfica");
        pintarContenedor(new PnlGrafo());
    }//GEN-LAST:event_btnGraficoActionPerformed

    private void btnKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKruskalActionPerformed
        this.setTitle("Grafo del estado de Puebla - MST Kruskal");
    }//GEN-LAST:event_btnKruskalActionPerformed

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
        this.setTitle("Grafo del estado de Puebla - MST Prim");
    }//GEN-LAST:event_btnPrimActionPerformed

    private void btnBoruvkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoruvkaActionPerformed
        this.setTitle("Grafo del estado de Puebla - MST Borůvka");
    }//GEN-LAST:event_btnBoruvkaActionPerformed

    private void btnBellmanFordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBellmanFordActionPerformed
        this.setTitle("Grafo del estado de Puebla - Ruta más corta Bellman-Ford");
        FrmElegirLocalidades elegirLocalidad = new FrmElegirLocalidades(this, "BELLMAN");
        elegirLocalidad.setVisible(true);
    }//GEN-LAST:event_btnBellmanFordActionPerformed

    private void btnDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDijkstraActionPerformed
        this.setTitle("Grafo del estado de Puebla - Ruta más corta Dijkstra");
        FrmElegirLocalidades elegirLocalidad = new FrmElegirLocalidades(this, "DIJKSTRA");
        elegirLocalidad.setVisible(true);
    }//GEN-LAST:event_btnDijkstraActionPerformed

    private void btnReportesComplejidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesComplejidadMouseClicked
        this.setTitle("Grafo del estado de Puebla - Reportes de complejidad");
    }//GEN-LAST:event_btnReportesComplejidadMouseClicked

    private void btnBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBFSActionPerformed
        this.setTitle("Grafo del estado de Puebla - Recorrido BFS");
    }//GEN-LAST:event_btnBFSActionPerformed

    private void btnDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDFSActionPerformed
        this.setTitle("Grafo del estado de Puebla - Recorrido DFS");
    }//GEN-LAST:event_btnDFSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bntRecorridos;
    private javax.swing.JMenuItem btnBFS;
    private javax.swing.JMenuItem btnBellmanFord;
    private javax.swing.JMenuItem btnBoruvka;
    private javax.swing.JMenuItem btnDFS;
    private javax.swing.JMenuItem btnDijkstra;
    private javax.swing.JMenuItem btnGrafico;
    private javax.swing.JMenu btnGrafo;
    private javax.swing.JMenu btnInicio;
    private javax.swing.JMenuItem btnKruskal;
    private javax.swing.JMenu btnMST;
    private javax.swing.JMenuItem btnPrim;
    private javax.swing.JMenu btnReportesComplejidad;
    private javax.swing.JMenu btnRuta;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JMenuItem btnTablaNodosAristas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JScrollPane pnlContenido;
    // End of variables declaration//GEN-END:variables
}
