package frames;

import grafo.GrafoPueblaUtil;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;

/**
 * Pantalla que permite visualizar el grafo como una tabla de nodos y aristas
 *
 * @author victoria
 */
public class FrmTablaGrafo extends javax.swing.JFrame {

    public FrmTablaGrafo() {
        initComponents();
        pnlContenido.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        pnlContenido.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        llenarTabla();
        this.setSize(700, 690);
        this.setLocationRelativeTo(null);
    }

    // método que permite llenar la tabla con todos los vértices del grafo, sus vértices adyacentes y el peso de las aristas
    // columna 1: localidad de origen
    // columna 2: localidad destino
    // columna 3: distancia entre ambas (en Km)
    private void llenarTabla() {
        agregarEstiloTabla();
        DefaultTableModel modelo = (DefaultTableModel) tblGrafo.getModel();
        modelo.setRowCount(0);

        // obtener los municipios (vértices del grafo)
        List<String> municipios = GrafoPueblaUtil.getMunicipios();
        for (String municipio : municipios) {
            // obtener los municipios con los que tiene una carretera.
            List<String> adyacentes = GrafoPueblaUtil.getConexiones(municipio);

            for (String adyacente : adyacentes) {
                // separar la distancia del nombre del municipio
                String[] partes = adyacente.split("\\(");
                String nombreAdyacente = partes[0]; // obtener nombre del municipio
                String distanciaArista = partes[1].replace("km)", "").trim(); // obtener distancia

                Object[] fila = new Object[3];
                fila[0] = municipio;
                fila[1] = nombreAdyacente;
                fila[2] = distanciaArista;

                modelo.addRow(fila);
            }

        }
    }

    private void agregarEstiloTabla() {
        // estilo del enabezado de la tabla
        JTableHeader encabezado = tblGrafo.getTableHeader();
        encabezado.setFont(new Font("Arial", Font.BOLD, 18));
        encabezado.setForeground(Color.BLACK);

        // estilo de las celdas
        tblGrafo.setFont(new Font("Arial", Font.PLAIN, 14));
        tblGrafo.setRowHeight(40);

        tblGrafo.setShowGrid(true); // agrega borde a las celdas
        tblGrafo.setGridColor(Color.GRAY);
        tblGrafo.setIntercellSpacing(new Dimension(15, 0)); // hace que el texto no esté tan pegado a la izquierda


    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenido = new javax.swing.JScrollPane();
        tblGrafo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlContenido.setBorder(null);
        pnlContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlContenido.setFont(new java.awt.Font("Beirut", 0, 14)); // NOI18N

        tblGrafo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblGrafo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Origen", "Destino", "Distancia (Km)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pnlContenido.setViewportView(tblGrafo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane pnlContenido;
    private javax.swing.JTable tblGrafo;
    // End of variables declaration//GEN-END:variables
}
